### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by POPOTINESU** [POPOTINESU/DroneFlightLog#28]
### 概要
アプリ作成に必要なタスクを作成しました。

### 実装予定の機能

- [x] MVPリリースまでに作成

- [x] ログイン機能

- [x] 飛行記録機能

- [x] グループ毎に使用できる機体を分けれる機能

- [x] プルダウンで地名を入力できる

- [x] ユーザー、グループ作成機能

- [x] 機体登録機能

本リリースまでに追加する機能

- [x] 定期点検通知機能

- [x] フライト時間計測機能

- [x] ストップウォッチで時間記録機能

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

ストーリーポイント5以上のものが散見されました。
ストーリーポイント1,2になるくらい細かくissue立てしましょう。細分化することで分かっていること、分かっていないことが明確化されることに加えて、進捗を感じながら開発を進めることができます。

**Comment by POPOTINESU** [comment]
> ストーリーポイント5以上のものが散見されました。
> ストーリーポイント1,2になるくらい細かくissue立てしましょう。細分化することで分かっていること、分かっていないことが明確化されることに加えて、進捗を感じながら開発を進めることができます。

ご指摘ありがとうございます。
issueを細分化して、ストーリーポイントを2以下になるように設定いたしましたので、
ご確認いただけますと幸いです。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
