### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by POPOTINESU** [POPOTINESU/DroneFlightLog#45]

**Comment by Mariko222** [comment]
お疲れ様です。
こちらご提出いただく際に提出テンプレートが用意されていたかと思いますので、そちらに則ってデプロイ済みアプリのURL共有とともに記載頂けたらと思います。
よろしくお願いします。

**Comment by POPOTINESU** [comment]
申し訳ございません。
下記に内容をテンプレートに従って、記載いたしましたのでご確認ください。


## 各種情報
DroneFlightLog
https://www.drone-flight-log.com/login

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ログイン機能
- [ ] 飛行記録機能
- [ ] グループ毎に使用できる機体を分けれる機能
- [ ] プルダウンで地名を入力できる
- [ ] ユーザー、グループ作成機能

## READMEレビュー時から変更した機能
-  プルダウンで地名を入力ではなく、GoogleMapsのAPIを叩いて現在位置を入力できるようにしました。
- ストップウォッチ形式より普通に入力で充分そうだったので減らしました。
- 資格も管理できるようにしていましたが、DIPSという国土交通省のアプリ(これは飛行申請時に皆使う)でその仕様があったので、抜かしました。

## サービスイメージがわかるようなスクリーンショット等
<img width="1439" alt="スクリーンショット 2024-07-13 14 57 38" src="https://github.com/user-attachments/assets/99e9ea53-143a-4e48-b82e-8bac577986b4">
ログイン画面

<img width="1433" alt="スクリーンショット 2024-07-13 14 58 55" src="https://github.com/user-attachments/assets/64b1878d-dfd6-443d-a62e-4faab6b5dbdf">
メイン画面

<img width="1436" alt="スクリーンショット 2024-07-13 14 59 54" src="https://github.com/user-attachments/assets/8265b57f-b4bd-4cd3-8ff7-5c67040372f0">
グループ作成１ページ目

<img width="1432" alt="スクリーンショット 2024-07-13 15 00 41" src="https://github.com/user-attachments/assets/81a0ab77-f86a-4cf9-a336-f7851636b480">
グループ作成２ページ目

<img width="1436" alt="スクリーンショット 2024-07-13 15 02 17" src="https://github.com/user-attachments/assets/a1d5d496-21ef-43bf-b21c-8125b5deaa2a">
グループ一覧( グループ名は気にしないでください…)

<img width="1429" alt="スクリーンショット 2024-07-13 15 03 04" src="https://github.com/user-attachments/assets/38d12a9e-f180-41cc-995b-13b01105009c">
グループ所属のユーザー

<img width="1431" alt="スクリーンショット 2024-07-13 15 03 27" src="https://github.com/user-attachments/assets/8400f1fa-5ed8-4027-9303-c3b923833b7a">
機体一覧


<img width="1433" alt="スクリーンショット 2024-07-13 15 04 06" src="https://github.com/user-attachments/assets/279f2873-d1f9-4e67-ac9d-de770be9dc7d">
パスワードリセット(メール送信画面)


<img width="1431" alt="スクリーンショット 2024-07-13 15 04 40" src="https://github.com/user-attachments/assets/3c0eecda-44f3-4417-ad97-5463e75c038d">
パスワードリセット画面

<img width="1421" alt="スクリーンショット 2024-07-13 15 07 40" src="https://github.com/user-attachments/assets/0ebbdb13-6328-424a-9798-98b6c1854a55">
新規飛行記録作成

<img width="1420" alt="スクリーンショット 2024-07-13 15 08 11" src="https://github.com/user-attachments/assets/55993b2d-11fb-4a81-a065-ff9095bed8eb">
新規飛行記録作成(現在位置を取得)

<img width="1426" alt="スクリーンショット 2024-07-13 15 06 41" src="https://github.com/user-attachments/assets/93d17cf8-0a2e-4ecb-8729-a1840482b12a">
飛行記録編集画面

**Comment by tarakish** [comment]
こちらユーザー登録ページで登録ボタンを押しても反応がありませんでした。
裏側では保存されていてページが遷移していない可能性を考えログインも試しましたが登録されていないようでした。
上記ご確認をお願いします。

**Comment by POPOTINESU** [comment]
確認したところ、renderを使っているので、スリープに入ってしまっていたようです。
また、前はうまくいっていたので気にしていなかったのですが、
samesiteの設定周りでうまくいっていなかったので、サブドメインを設定して解決しました。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
